robotology/wearables

- XSensMVN/src/XSensMVNCalibrator.cpp
I found out what seems to be the problem with the `XsensMVNCalibrator` device when trying to discard the old calibration and recalibrate.
After discarding the old calibration there is a while loop waiting for discard operation to be completed (see https://github.com/robotology-playground/wearables/blob/feature/cleanup/XSensMVN/src/XSensMVNCalibrator.cpp#L171).
The termination of the waiting loop is determined by `m_operationCompleted` flag which is set to `true` by xsens callbacks [`onCalibrationAborted `](https://github.com/robotology-playground/wearables/blob/feature/cleanup/XSensMVN/src/XSensMVNCalibrator.cpp#L338), [`onCalibrationComplete `](https://github.com/robotology-playground/wearables/blob/feature/cleanup/XSensMVN/src/XSensMVNCalibrator.cpp#L341), and [`onCalibrationProcessed …
> Fix Xsens Calibrator device

- CMakeLists.txt
Small fixies to the CMakeLists:
- remove copy-paste leftover from `WBToolbox`
- remove `if(NOT BUILD_SHARED_LIBS)` for `CMAKE_POSITION_INDEPENDENT_CODE ` (see https://github.com/robotology/human-dynamics-estimation/pull/87#discussion_r246760173)
- use `YARP_FORCE_DYNAMIC_PLUGINS ` instead of overriting `BUILD_SHARED_LIBS `
(copy of https://github.com/robotology-playground/wearables/pull/17)
> Fix CMakeLists with YARP_FORCE_DYNAMIC_PLUGINS

- devices/IWearRemapper/include/IWearRemapper.h
- devices/IWearRemapper/src/IWearRemapper.cpp
In order to be able to use Wearable data that are streamed trough [`yarpdataplayer`](https://www.yarp.it/yarpdataplayer.html), this PR introduces an **optional** parameter `useRPC` that allows to the need of an `rpc` port from wearable data.
> set rpc port in IWearRemapper optional

- devices/IWearRemapper/src/IWearRemapper.cpp
As discussed in https://github.com/robotology-playground/wearables/issues/27#issuecomment-467059753, I am removing the output port of the `IWearRemapper` device.
In order to dump the data from an `IWearRemapper`, it will be now necessary to use an `IWearWrapper` attached to the `IWearRemapper` device.
> remove output port from IWearRemapper

- devices/IWearRemapper/src/IWearRemapper.cpp
- wrappers/IWear/src/IWearWrapper.cpp
Following the observations in https://github.com/robotology/wearables/issues/43, The `IWearRemapper` and `IWearWrapper` are observed to consider only to status: `OK` and `ERROR`(not `OK`). Furthermore, in case the state is not `OK`, both the device stop running which means that any other status (`Overflow` and `Timeout`) are not considered.
The changes in this PR tries to improve the current implementation in order to stream the data for the two status `Overflow` and `Timeout` (while in the case the status is `Error` the devices are stopped).
> Improve IWearWrapper and IWearRemapper status error handling

- devices/IAnalogSensorToIWear/src/IAnalogSensorToIWear.cpp
Following https://github.com/robotology/wearables/issues/43, with this PR I want to improve the handling of error status in `IAnalogSensorToIWear`.
**IAnalog sensor status**
To sum-up, an [`IAnalogSensor`](https://github.com/robotology/yarp/blob/master/src/libYARP_dev/include/yarp/dev/IAnalogSensor.h) has multiple channels, and each channel has a state that can be accessed through [`getState(idx)`](https://github.com/robotology/yarp/blob/master/src/libYARP_dev/include/yarp/dev/IAnalogSensor.h#L57) (possible states: `OK`, `ERROR`, `OVERFLOW`, `TIMEOUT`). Plus, the [`read()`](https://github.com/robotology/yarp/blob/master/src/libYARP_dev/include/yarp/dev/IAnalogSensor.h#L50) method also return a value of the status of the `IAnalogSensor` which depends on how it is implemented at the device …
> Improve IAnalogSensorToIWear error handlings

- .ci/install.sh
- .travis.yml
Given that the compatibility with YARP `master` branch was fixed (https://github.com/robotology/wearables/issues/46) I am restoring the standard CI branch dependencies. I am also removing the dependency on icub `devel` since probably the reason for that dependency is now solved.
> restore CI branch deps

- doc/How-to-run-FTshoes.md
- doc/How-to-run-XsensSuit.md
- doc/README.md
With this PR I am adding some documentation on how to run some wearable devices.
This documentation is an updated version of the older documentation contained in https://github.com/robotology/human-dynamics-estimation/wiki/Human-Dynamics-Estimation-IWear-Source-Devices, in this way we also separate the documentation for the two repo and we can remove old documentation.
@Yeshasvitvs @diegoferigo
> Add documentation on how to run werable devices

- app/xml/applications/WearableDevices-Dumper.xml
This PR add an application for dumping the wearable data with the objective of trying to take out wearable related applications from [HDE applications](https://github.com/robotology/human-dynamics-estimation/tree/master/conf/xml/applications) in order to clean it up.
> Add wearable data dumper application

- devices/XsensSuit/src/XsensSuit.cpp
as noticed in https://github.com/robotology/wearables/issues/40#issuecomment-555006582 the value passed trough configuration was actually not used.
> Fix sampling-rate passing trough configuration

- app/xml/AMTIForcePlatesWearableDevice.xml
This PR adds the configuration file to use the [AMTI force platforms](https://github.com/robotology/forcetorque-yarp-devices/tree/master/amti) as the source for force/torque measurements, and outputs the wearable data in the same format as the FTShoes, with the same output port names. This choice was made as to not make any changes in the [configuration files of human-dynamics-estimation](https://github.com/robotology/human-dynamics-estimation/blob/master/conf/xml/Human.xml). So, essentially AMTI force platforms can be used as an alternative source of force/torque measurements to substitute for FTShoes
Following the similar test done in https://github.com/robotology/forcetorque-yarp-devices/pull/20, the output force/torque measurements streamed as wearable data is as following:
**NOTE:** …
> Add AMTI wearable configuration file

- .ci/brewInstallOrUpgrade.sh
- .travis.yml
Fix MacOS CI as done in https://github.com/robotology/human-dynamics-estimation/pull/216.
> Fix MacOS CI

- app/xml/applications/HumanDynamicsEstimation-WearableDumper.xml
This PR adds a yarp manager application configuration file to save Xsens suit and FTShoes wearable data through yarp data daumper, to run human dynamics estimation tests offline.
> Add wearable yarp dumper application to run HDE offline

- CHANGELOG.md
- devices/IAnalogSensorToIWear/CMakeLists.txt
- devices/ICub/CMakeLists.txt
- devices/IWearRemapper/CMakeLists.txt
- devices/Paexo/CMakeLists.txt
- devices/XsensSuit/CMakeLists.txt
- interfaces/IWear/CMakeLists.txt
- wrappers/IWear/CMakeLists.txt
- wrappers/IXsensMVNControl/CMakeLists.txt
This patch addresses the following two compile time warnings:
-  `yarp_prepare_plugin` header file path
- `IWear` interface relative path to files
The patch results in clean compilation
> Cleanup plugin headers and IWear interface warning

- CHANGELOG.md
- CMakeLists.txt
If one wants to specify additional linked flags, those should be appended to [`CMAKE_SHARED_LINKER_FLAGS`](https://cmake.org/cmake/help/latest/variable/CMAKE_SHARED_LINKER_FLAGS.html), not overwrite it as this would lead to the [`LDFLAGS`  environment variable](https://cmake.org/cmake/help/latest/envvar/LDFLAGS.html) to be ignored, leading to linking errors in some environments (for example conda).
For more details see:
* https://github.com/osrf/gazebo/pull/2922
* https://github.com/robotology/robotology-superbuild/issues/681#issuecomment-817274209
It would be convenient to tag a released after this fix is integrated to fix the conda binary generation at the robotology-superbuild level (see  https://github.com/robotology/robotology-superbuild/issues/681). Let me know if you want to do …
> Do not overwrite default linker flags so that LDFLAGS environment variable is considered

- .github/workflows/ci.yml
- CHANGELOG.md
- CMakeLists.txt
- app/xml/iWearLoggerExampleTemplate.xml
- cmake/AddInstallRPATHSupport.cmake
- wrappers/CMakeLists.txt
- wrappers/IWearLogger/CMakeLists.txt
- wrappers/IWearLogger/include/IWearLogger.h
- wrappers/IWearLogger/src/IWearLogger.cpp
This PR,
- adds an `AddInstallRPATHSupport` cmake module that was required to load the shared objects privately linked by the YARP device plugin.
- adds an `iwear_logger` wrapper device that can be attached to any wearable producer to log the data from all the sensors associated with the producer. 
At the heart of its implementation, It replaces,
> the `iwear_wrapper`'s logic of encapsulating the wearable sensors data into a WearableData msg and passing through a YARP port 
with 
> `yarp-telemetry`'s logic of dumping the data into a mat file.
A template for configuring the `iwear_logger` wrapper device can be as follows,
``` xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE robot PUBLIC "-//YARP//DTD yarprobotinterface 3.0//EN" "http://www.yarp.it/DTD/yarprobotinterfaceV3.0.dtd"> …
```
> Add iwear_logger wrapper device and AddInstallRPathSupport cmake module

- CHANGELOG.md
- XSensMVN/include/XSensMVNDriver.h
- XSensMVN/src/XSensMVNDriverImpl.cpp
- app/xml/XsensSuitWearableDevice.xml
- devices/XsensSuit/src/XsensSuit.cpp
This PR adds the option of `saveCurrentCalibration` to Xsens wearable device
The saved calibration file is with `.mvn` file extension
CC @lrapetti @claudia-lat @DanielePucci
> Add Xsens saveCurrentCalibration option

- CHANGELOG.md
- app/xml/iWearLoggerExampleTemplate.xml
- wrappers/IWearLogger/CMakeLists.txt
- wrappers/IWearLogger/src/IWearLogger.cpp
This PR updates `iwear_logger` device with optional streaming of data to yarp ports. This has been tested using `iFeel` node data
https://user-images.githubusercontent.com/6505998/122778008-e0a43d80-d2ac-11eb-836f-5f6b069ad791.mp4
CC @prashanthr05 @lrapetti @claudia-lat @DanielePucci
> Update IWear Logger with Yarp port streaming

- CHANGELOG.md
- app/xml/iWearLoggerExampleTemplate.xml
- devices/Paexo/conf/Paexo.xml
- devices/Paexo/conf/paexo-validation-motor-control.sh
- devices/Paexo/src/Paexo.cpp
- devices/Paexo/test-application/paexo-test-application.cpp
- wrappers/IWearLogger/src/IWearLogger.cpp
This PR updates Paexo wearable device with motor control through yarp and addresses https://github.com/robotology/wearables/issues/109
CC @claudia-lat @lrapetti @DanielePucci
> Update Paexo wearable device with motor control through yarp

- interfaces/IWear/CMakeLists.txt
PR https://github.com/robotology/wearables/pull/126 move the `Wearable/IWear/Sensors/Utils.h` include to `Wearable/IWear/Utils.h`. However, this change was not accounted for in the installation rules,  neither documented in the CHANGELOG. This PR fixes the first issue to fix https://github.com/robotology/robotology-superbuild/issues/846 .
> Fix installation of Wearable/IWear/Utils.h install

- CHANGELOG.md
- app/xml/iWearLoggerExampleTemplate.xml
- devices/IWearRemapper/src/IWearRemapper.cpp
- msgs/thrift/WearableData.thrift
- wrappers/IWear/src/IWearWrapper.cpp
- wrappers/IWearLogger/src/IWearLogger.cpp
Opening this PR to add the management of ISkinSensors.
The definition of the message has been updated to hold a vector of double representing the pressure data exerted on the skin taxels.
`IWearWrapper`, `IWearRemapper` and `IWearLogger` have been updated accordingly.
The implementation has been tested in the context of https://github.com/ami-iit/element_stretchable-insole/issues/134.
> Add ISkinSensor management

- wrappers/IWear/src/IWearWrapper.cpp
Currently, when a measurement is not available and the `get${Data}` methods return false, the `IWearRemapper` was rasing a warning, but was also updating the buffer with some uninitialized variables.
This PR fix this issue.
In the future e could improve the behaviour in this cases by properly using the status variable (but then we should avoid that downstream device do not stop if for example simply few data are missing).
> Fix IWearWrapper behaviour when read measurement fails

- .github/workflows/ci.yml
- CHANGELOG.md
- CMakeLists.txt
- devices/CMakeLists.txt
This PR to disable the building of the XsensSuit device by default on Windows, since one may want to use the wearable library without it.
I also changed the name of the `XSENS_MVN_USE_SDK` option to  `Enable_XsensSuit` to be in line with the other devices.
One thing that can be done is enabling the option by default only if `XsensXME` is found.
> Disable default enabling of XsensSuit device 

- README.md
- wrappers/IWearLogger/CMakeLists.txt
This PR to enhance the documentation related to `IWearLogger`.
As for now, it is not built/installed if `yarp-telemetry` is missing. In order to make users aware of that, I added the info on the README's dependencies section. I also added a CMake warning message for the same purpose.
> Add dependencies for IWearLogger in the documentation

- .github/workflows/ci.yml
Fixing the CI (see failure at https://github.com/robotology/wearables/runs/6267391127?check_suite_focus=true)
> Update matioCpp and yarp-telemetry versions in CI

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- wrappers/IWearLogger/CMakeLists.txt
- wrappers/IWearLogger/src/IWearLogger.cpp
See https://github.com/robotology/robometry/pull/173
Please review code.
> Migrate from YARP_telemetry to robometry

- .github/workflows/ci.yml
It is possible because now the conda packages of robometry are available: https://anaconda.org/robotology/robometry.
It fixes #156
> Restore robometry in the windows ci

- CHANGELOG.md
- CMakeLists.txt
- README.md
- devices/CMakeLists.txt
- wrappers/CMakeLists.txt
- wrappers/IWearLogger/CMakeLists.txt
This PR improves the usage of cmake flags for the installation of optional software components in wearables, trying to unify the behaviour.
In particular:
- avoids hidden `if` selecting software components
- change default flags values depending on the found dependencies
The documentation is also updated and improved accordingly
> Improve cmake installation flags

- CHANGELOG.md
- msgs/CMakeLists.txt
WearableData messages interface is not currently installed. This PR to install them as done for the WearableActuators.
However, this is *not* the correct way to install the files, since they are under `${CMAKE_INSTALL_PREFIX}/thrifts`.
I will open an issue for that.
> Install WearableData interface

- CHANGELOG.md
- msgs/thrift/WearableActuators.thrift
This PR to remove unused definitions for actuators message.
Currently, the following line will not compile:
```c++
#include <thrift/WearableData.h>
#include <thrift/WearableActuatorCommand.h>
int main()
{
return 0;
}
```
With the following message:
```bash
In file included from <superbuild-dir>/build/install/include/thrift/ActuatorInfo.h:16,
from <superbuild-dir>/build/install/include/thrift/WearableActuatorCommand.h:16,
from myCode.cpp:13:
<superbuild-dir>/build/install/include/thrift/ActuatorStatus.h:21:13: error: ‘ERROR’ conflicts with a previous declaration
21 |     ERROR = 0,
|             ^
In file included from <superbuild-dir>/build/install/include/thrift/SensorInfo.h:16,
from <superbuild-dir>/build/install/include/thrift/Accelerometer.h:16,
from …
```
> Remove unused actuators message definitions

- CHANGELOG.md
- devices/IWearRemapper/include/IWearRemapper.h
- devices/IWearRemapper/src/IWearRemapper.cpp
Until now, the IWear remapper had the dual role of **network client** (converting yarp port to interface) and **remapper** (merging multiple signals). 
This PR extend the IWearRemapper capabilities concerning the second role (**remapping**) enabling it to merge multiple interfaces (until now it was only capable of merging signals from ports). In the future the other role (**network client**) might be delegated to a dedicated device.
As a consequence of this change:
- The `IWearRemapper` inherit from IMultipleWrapper (see [here](https://github.com/robotology/wearables/commit/2beda7472fc37660643b4090afafb70ac8def998#diff-128791d37501a3ed0419157fd075de56bbe657fec48eceee92686d964991d6f4R36) and can be attached to IWear interfaces (see …
> Allow IWearRemapper to attach and remap IWear interfaces

- CHANGELOG.md
- devices/HapticGlove/conf/HapticGlove.xml
- devices/HapticGlove/src/HapticGlove.cpp
> Fix period management in HapticGlove

- CHANGELOG.md
- bindings/python/msgs/CMakeLists.txt
- devices/IWearRemapper/CMakeLists.txt
- devices/IWearRemapper/include/IWearRemapper.h
- devices/IWearRemapper/src/IWearRemapper.cpp
- devices/Paexo/test-application/CMakeLists.txt
- msgs/CMakeLists.txt
- wrappers/IWearActuators/CMakeLists.txt
This PR introduces the following 2 changes in `IWearRemapper`:
- Fixed use of mutex when reading the port in https://github.com/robotology/wearables/pull/174/commits/d90cc76692e545ba5e9a41a3227a5ee4a8ae01a1
- Switch to use  `std::mutex` instead of `std::recursive_mutex` in https://github.com/robotology/wearables/pull/174/commits/3c3a4d7902aba66e86e1384277ad294700fe1413
-  Fixed first read check from all ports in https://github.com/robotology/wearables/pull/174/commits/9661562c8695de64482e8fab88a1568424bd1902
> Use std::mutex instead of std::recursive_mutex in IWearRemapper

- devices/HapticGlove/include/HapticGlove.h
- devices/IAnalogSensorToIWear/include/IAnalogSensorToIWear.h
- devices/ICub/include/ICub.h
- devices/IFrameTransformToIWear/include/IFrameTransformToIWear.h
- devices/IWearRemapper/include/IWearRemapper.h
- devices/IWearRemapper/src/IWearRemapper.cpp
- devices/Paexo/include/Paexo.h
- devices/XsensSuit/include/XsensSuit.h
- wrappers/IWear/include/IWearWrapper.h
- wrappers/IWear/src/IWearWrapper.cpp
- wrappers/IWearActuators/include/IWearActuatorsWrapper.h
- wrappers/IWearLogger/include/IWearLogger.h
- wrappers/IWearLogger/src/IWearLogger.cpp
- wrappers/IXsensMVNControl/include/IXsensMVNControlWrapper.h
Removing deprecated YARP headers (see https://github.com/robotology/wearables/issues/177)
> Remove deprecated YARP headers

- .github/workflows/ci.yml
This PR addresses latest failures in the CI (e.g. https://github.com/robotology/wearables/actions/runs/3672094157) due to the apt-depencencies build job. 
Looks like the package `python-dev` has been removed in favor of either `python3-dev` or `python2-dev`.
> Fix CI failure

- CHANGELOG.md
- wrappers/IWear/src/IWearWrapper.cpp
- wrappers/IWearLogger/src/IWearLogger.cpp
As per title, this PR to fix a typo in `IWearWrapper` and `IWearLogger` that were using the same `get` call for the emg signal its normalization value.
> Fix typo in IWearWrapper and IWearLogger

- CHANGELOG.md
- CMakeLists.txt
- Fixed EMG normalization value in IWearWrapper and IWearLogger (https://github.com/robotology/wearables/pull/186).
- Fixed IWearLogger termination when `BufferManager` configuration fails (https://github.com/robotology/wearables/pull/195).
- The license of the repo changed to [`BSD-3-Clause`](https://spdx.org/licenses/BSD-3-Clause.html) (https://github.com/robotology/wearables/pull/192).
> Bump wearables version to 1.7.2

- CHANGELOG.md
- bindings/CMakeLists.txt
By setting the WEARABLES_PYTHON_INSTALL_DIR CMake variable.
> CMake: Permit to explicitly specify Python installation directory

- .github/workflows/ci.yml
- ci_env.yml
This PR addresses #198  and #199. (Additionally it cleans the the CI file)
> Switch CI from miniconda to micromamba and remove homebrew

- CHANGELOG.md
- CMakeLists.txt
- Update iframetransform_to_iwear.xml to use new TF device (https://github.com/robotology/wearables/pull/202)
- CMake: Permit to explictly specify Python installation directory by setting the `WEARABLES_PYTHON_INSTALL_DIR` CMake variable (https://github.com/robotology/wearables/pull/197).
> Bump wearables version to 1.8.0

- devices/Paexo/src/Paexo.cpp
- wrappers/IWearActuators/src/IWearActuatorsWrapper.cpp
* `serialComPortName` is unused, so we remove it
* `attachedWearableDeviceName` is actually used for some print information, but it is not particular useful to print the `device`, as if you have multiple devices (for example, a left and right couple of device) both they will have the same `device` value. Instead, it is more useful to print the key that have been passed to the `attachAll` method, that is the name attribute of the `elem` tag child of the in the attach-related element of the yarprobotinterface xml, see for example https://github.com/robotology/wearables/blob/3d57b0b3dd9dae5293cbd5690f91dec4c473dd43/devices/HapticGlove/conf/HapticGlove.xml#L72 .
Fix https://github.com/robotology/wearables/issues/205 .
> Fix compatibility with YARP 3.10

- .github/workflows/ci.yml
To fix the problem reported in https://github.com/ami-iit/matio-cpp/issues/78 that occurred in CI.
> Bump matio-cpp in CI to v0.2.4

- wrappers/IWearActuators/src/IWearActuatorsWrapper.cpp
This PR fixed the IF statement where it checks the actuator port names. 
cc @S-Dafarra
> Fixed port name check if-statement logic
