devices/IWearRemapper/include/IWearRemapper.h, devices/IWearRemapper/src/IWearRemapper.cpp, wrappers/IWear/include/IWearWrapper.h, wrappers/IWear/src/IWearWrapper.cpp
This PR fixes the termination errors mentioned in https://github.com/robotology/wearables/issues/37, accordingly to the changes in done by @Yeshasvitvs in the branch [`fix/update-termination-process`](https://github.com/robotology/wearables/tree/fix/update-termination-process) (that was left behind master for too long)
=> Fix termination new

app/xml/FTShoeLeftWearableDevice.xml, app/xml/FTShoeRightWearableDevice.xml, app/xml/FTShoesWearableDevice.xml, app/xml/ICubWearableDevice.xml, app/xml/SkinInsolesWearableDevice.xml, app/xml/XsensSuitWearableDevice.xml, conf/Xsens/XsensAwindaSuitWearableDevice.xml, conf/Xsens/XsensLinkSuitWearableDevice.xml
Required by `YARP3.2` (after https://github.com/robotology/yarp/pull/2042 )
=> update DTD configuration files

CHANGELOG.md
As discussed in https://github.com/robotology/wearables/issues/73
=> Create CHANGELOG.md and release version 1.0.0

CHANGELOG.md, app/CMakeLists.txt
Currently the data dumper application is not installed, and I am adding it with this PR.
=> Add Wearable devices dumper application Installation

CHANGELOG.md, README.md
With this PR I improve the readme by adding missing information regarding the dependencies and the compilation.
=> Improve README.md

CHANGELOG.md, CMakeLists.txt
New release following https://github.com/robotology/wearables/pull/110
=> Bump wearables version to 1.2.1

wrappers/IWearLogger/include/IWearLogger.h, wrappers/IWearLogger/src/IWearLogger.cpp
This PR introduce clang-format changes to the IWearLogger files.
@lrapetti @diegoferigo there are indeed multiple changes, would you rather have someone else author these commits? Or maybe the maintainer could introduce these changes repository wide?
Let me know, we can close this PR accordingly.
=> IWearLogger: Reformat files with clang-format

.github/workflows/ci.yml
As discussed in https://github.com/robotology/wearables/issues/114
=> Change Windows CI to conda

CHANGELOG.md, CMakeLists.txt, README.md, devices/Paexo/CMakeLists.txt, devices/Paexo/conf/Paexo.xml, devices/Paexo/conf/paexo-cmake-config.h.in, devices/Paexo/conf/paexo-validation-motor-control.sh, devices/Paexo/include/Paexo.h, devices/Paexo/src/Paexo.cpp
This PR updates the Paexo wearable device with FT sensors through iFeel system.
CC @evalli-iit @lrapetti @claudia-lat @DanielePucci 
https://user-images.githubusercontent.com/6505998/119797832-df186d00-beda-11eb-86f5-f241b46bc59f.mp4
=> Update Paexo wearable device with FT sensors

CHANGELOG.md, CMakeLists.txt
=> Bump wearables version to 1.3.0

.github/workflows/ci.yml, CHANGELOG.md, XSensMVN/src/XSensMVNDriverImpl_BCKP.cpp, devices/IAnalogSensorToIWear/src/IAnalogSensorToIWear.cpp, devices/ICub/src/ICub.cpp, devices/Paexo/src/Paexo.cpp, devices/XsensSuit/src/XsensSuit.cpp, modules/IWearFrameVisualizer/src/main.cpp
Replacing deprecated methods as pointed in https://github.com/robotology/wearables/issues/151.
=> Fix deprecated `yarp` functions

CHANGELOG.md, CMakeLists.txt
New release following https://github.com/robotology/wearables/pull/155
=> Bump wearables version to 1.4.0

.github/workflows/ci.yml, CHANGELOG.md, CMakeLists.txt, README.md, bindings/CMakeLists.txt, bindings/python/CMakeLists.txt, bindings/python/msgs/CMakeLists.txt, bindings/python/msgs/include/Wearable/bindings/msgs/BufferedPort.h, bindings/python/msgs/include/Wearable/bindings/msgs/Module.h, bindings/python/msgs/include/Wearable/bindings/msgs/WearableData.h, bindings/python/msgs/src/Module.cpp, bindings/python/msgs/src/WearableData.cpp, bindings/python/wearables.cpp, cmake/AddWearablesPythonModule.cmake, cmake/FindPython/Support.cmake, cmake/FindPython3.cmake
With this PR it will be possible to get and send the WearableData message via python and thanks to [this](https://it.mathworks.com/help/matlab/matlab_external/ways-to-call-python-from-matlab.html) in MATLAB
```python
import yarp
import wearables.bindings as wearables
network = yarp.Network()
network.init()
port = wearables.msg.BufferedPortWearableData()
port.open("/foo")
data = port.read(False)
```
On matlab
```matlab
%% Initialize the YARP Network and collect data.
clear; clc;
network = yarp.Network()
network.init()
py.importlib.import_module('wearables.bindings');
port = py.wearables.bindings.msg.BufferedPortWearableData();
port.open("/foo"); % Opening port named '/foo'
% Remember to connect the ports. Command line is the following:
% yarp connect /iFeelSuit/WearableData/data:o /foo …
```
=> Implement the python bindings for the WearableData msg

CHANGELOG.md, CMakeLists.txt
New release containing Python Bindings thanks to @GiulioRomualdi  (https://github.com/robotology/wearables/pull/162)
=> Bump wearables version to 1.5.0

devices/HapticGlove/src/HapticGlove.cpp
=> Use yTrace instead of yInfo for debug prints

.github/workflows/ci.yml
=> Fix stable tag of robometry in CI

.github/CODEOWNERS, README.md
Adding @lrapetti and @RiccardoGrieco as repo maintainers
=> Add maintainers information

CHANGELOG.md, CMakeLists.txt
=> Bump version to v1.7.1

.github/workflows/ci.yml
=> Update CI tags

CHANGELOG.md, devices/IFrameTransformToIWear/conf/iframetransform_to_iwear.xml
=> Update iframetransform_to_iwear.xml to use new TF device

CHANGELOG.md
Following https://github.com/robotology/idyntree/pull/1162
=> Stop using CHANGELOG.md

.gitignore, devices/IWearRemapper/src/IWearRemapper.cpp
Fixes: https://github.com/robotology/wearables/issues/208
=> Allow specifying local ports in IWearRemapper
